---
  # Tasks to backup database

- name: Dump {{ mariadb_db_name }}.sql
  mysql_db:
    state: dump
    name: "{{ mariadb_db_name }}"
    target: "/tmp/{{ mariadb_db_name }}.sql"
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Email {{ mariadb_db_name }}.sql backup
  mail:
    host: "{{ admin_email_server }}"
    port: 587
    username: "{{ admin_email }}"
    password: "{{ admin_email_password }}"
    to: "{{ admin_name }} <{{ admin_email }}>"
    subject: "Backup of {{ mariadb_db_name }} on {{ ansible_hostname }}"
    body: "Backup of {{ mariadb_db_name }} on {{ ansible_hostname }}"
    attach: "/tmp/{{ mariadb_db_name }}.sql"

- name: Copy {{ mariadb_db_name }}.sql backup to local machine
  synchronize:
    mode: pull
    src: "/tmp/{{ mariadb_db_name }}.sql"
    dest: "{{ mariadb_db_backup_dir }}/"
  delegate_to: localhost
