---
  # WORK IN PROGRESS
  # Tasks to backup database

- name: Dump {{ mariadb_db_name }}.sql
  mysql_db:
    state: dump
    name: "{{ mariadb_db_name }}"
    target: "/tmp/{{ mariadb_db_name }}.sql"
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Email {{ mariadb_db_name }}.sql backup
  mail:
    host: localhost
    port: 25
    to: "{{ admin_name }} <{{ admin_email }}>"
    subject: "Backup of {{ mariadb_db_name }} on {{ ansible_hostname }}"
    body: "Backup of {{ mariadb_db_name }} on {{ ansible_hostname }}"
    attach: "/tmp/{{ mariadb_db_name }}.sql"
    secure: starttls
